name: Build

on:
  push:
    branches:
      - '*micromamba'

jobs:
  # Build image
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mamba_ver: [latest, 1.1.0, 1.0.0]
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "./micromamba"
          file: "./micromamba/Dockerfile"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/micromamba:${{ matrix.mamba_ver }}
          build-args: |
            MAMBA_VERSION=${{ matrix.mamba_ver }}
      - 
        name: Update description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/micromamba
          readme-filepath: ./micromamba/README.md